#!/bin/bash
#
# Copyright (C) 2022 Nagisa Sekiguchi
# Distributed under the GNU General Public License, version 2.0.
#
# Conceptually based on git-completion.tcsh (https://github.com/git/git/blob/master/contrib/completion/git-completion.tcsh)
# Run and get result of bash completion script (also support bash-completion aware script)
#
# usage: $0 [full path of bash_completion] [full path of completion script] [target function] [comp line]


# load `bash_completion`
complete() { true; }   # ignore `complete` function
compopt() { true; }    # FIXME: emulate `-o option`
BASH_COMPLETION_COMPAT_DIR=/dev/null
BASH_COMPLETION_USER_FILE=/dev/null
source "$1"

# load completion script
source "$2"

# load comp line
COMP_WORDS=($4)
if [ "${4: -1}" == " " ]; then
	# The last character is a space, so our location is at the end
	# of the command-line array
	COMP_CWORD=${#COMP_WORDS[@]}
else
	# The last character is not a space, so our location is on the
	# last word of the command-line array, so we must decrement the
	# count by 1
	COMP_CWORD=$((${#COMP_WORDS[@]}-1))
fi
COMP_LINE="$4"
COMP_POINT=${#COMP_LINE}


# call completion function
eval "$3" "$(basename ${COMP_WORDS[0]})"

IFS=$'\n'
echo "${COMPREPLY[*]}"
